version: "3.1"

services:
  jupyternotebook:
    image: 806490324596.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest
    build:
      context: jupyternotebook
      dockerfile: ./Dockerfile
    # command: python server.py
    ports:
      - 0.0.0.0:8888:8888
      - 0.0.0.0:3000:3000
    links:
      - mysql:mysql
    volumes:
      - $PWD/app:/root/app
    working_dir: /root/app
    restart: unless-stopped # 最後の状態が終了ステータスだったら再起動しない
    networks:
      - employee_link

  mysql:
    build:
      context: mysql
      dockerfile: ./Dockerfile
    ports:
      - 0.0.0.0:3001:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    restart: unless-stopped
    networks:
      - employee_link

networks:
  employee_link:
    external: true
